---
- name: Install Patroni
  ansible.builtin.include_tasks:
    file: 'install.yml'
- name: Configure Patroni
  ansible.builtin.include_tasks:
    file: 'configure.yml'
- name: Check Patroni health
  ansible.builtin.include_tasks:
    file: 'health_check.yml'