---
- name: Install dependencies (Debian)
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - runc
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - wget
  when: ansible_os_family == 'Debian'

- name: Disable swap (systemd)
  command: swapoff -a

- name: Disable swap on fstab
  shell: |
    swapoff -a
    sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- name: Load kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop: "{{ kernel_modules }}"

- name: Add kernel modules to load at boot
  lineinfile:
    path: /etc/modules-load.d/kubernetes.conf
    line: "{{ item }}"
    create: yes
  loop: "{{ kernel_modules }}"

- name: Configure sysctl parameters
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  loop: "{{ sysctl_params | dict2items }}"

- name: Configure sysctl parameters file
  blockinfile:
    path: /etc/sysctl.d/kubernetes.conf
    block: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward = 1
    create: yes

- name: Configure firewall for Kubernetes
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ kubernetes_allowed_ports }}"
  when: ansible_os_family == "Debian"