# Teleport
teleport_version: "v17.5.2"
teleport_architecture: "amd64"

# Teleport node settings
teleport_nodename: "{{ inventory_hostname }}"
teleport_advertise_ip: "{{ ansible_host }}"

# Teleport proxy settings
teleport_proxy_public_domain: ""
teleport_proxy_public_port: 443
teleport_proxy_https_cert_file: "/etc/teleport/ssl/fullchain.pem"
teleport_proxy_https_key_file: "/etc/teleport/ssl/privkey.pem"
teleport_proxy_web_listen_port: 443

# Teleport user and group
teleport_user: "teleport"
teleport_group: "teleport"

# Directories
teleport_install_dir: "/usr/local/bin"
teleport_config_dir: "/etc/teleport"
teleport_data_dir: "/var/lib/teleport"
teleport_log_dir: "/var/log/teleport"
teleport_ssl_dir: "/etc/teleport/ssl"

# Teleport configuration file
teleport_config_file: "/etc/teleport/teleport.yaml"

# Teleport log settings
teleport_log_level: "INFO"  # Options: DEBUG, INFO, WARN, ERROR, FATAL
teleport_log_file: "/var/log/teleport/teleport.log"
teleport_log_format: "json"

# Teleport cluster settings
teleport_cluster_name: "teleport-cluster"
teleport_cluster_enabled: true
