# Consul
consul_version: "1.21.2"
consul_arch: "amd64"

# Consul download URL
consul_download_url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_{{ consul_arch }}.zip"

# Consul user and group
consul_user: "consul"
consul_group: "consul"

# Consul directories
consul_install_dir: "/usr/local/bin"
consul_config_dir: "/etc/consul.d"
consul_ssl_dir: "{{ consul_config_dir }}/ssl"
consul_data_dir: "/opt/consul/data"
consul_log_dir: "/var/log/consul"

# Consul configuration settings
consul_server: true  # Set to true for server nodes
consul_config_file: "{{ consul_config_dir }}/consul.hcl"
consul_log_level: "WARN"
consul_log_json: true  # Enable JSON logging
consul_ui_enabled: true  # Enable Consul UI
consul_connect_enabled: true  # Enable Consul Connect
consul_performance_raft_multiplier: 1  # Raft multiplier for performance tuning

# Consul ports
consul_http_port: 8500
consul_https_port: 8501
consul_grpc_port: 8502
consul_grpc_tls_port: 8503
consul_dns_port: 8600

# Consul cluster settings
consul_datacenter: "dc1"
consul_cluster_name: "consul-cluster"
consul_node_name: "{{ inventory_hostname }}"

# Consul network settings
consul_advertise_addr: "{{ ansible_host }}"
consul_bind_address: "{{ ansible_host }}"
consul_client_address: "0.0.0.0"
consul_retry_join: "{{ groups['consul'] | difference([inventory_hostname]) | map('extract', hostvars, 'ansible_default_ipv4') | map(attribute='address') | list }}"

# Consul encryption settings
consul_encrypt: true  # Enable encryption for Consul communication
consul_encrypt_key: ""  # If empty, a new key will be generated

# Consul ACL settings
consul_acl_enabled: true  # Enable ACLs
consul_acl_default_policy: "deny"  # Default ACL policy

# Consul TLS settings
consul_tls_enabled: true  # Enable TLS for Consul
consul_tls_ca_file: "/usr/local/share/ca-certificates/consul-ca.crt"
consul_tls_cert_file: "{{ consul_ssl_dir }}/consul.crt"
consul_tls_key_file: "{{ consul_ssl_dir }}/consul.key"
consul_tls_verify_server_hostname: true  # Verify server hostname in TLS