---
- name: Install dependencies (Debian)
  ansible.builtin.package:
    name:
      - unzip
      - gnupg
      - openssl
    state: present
  when: ansible_os_family == 'Debian'

- name: Download Vault
  ansible.builtin.get_url:
    url: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_{{ vault_arch }}.zip"
    dest: "/tmp/vault.zip"
    checksum: "sha256:https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_SHA256SUMS"

- name: Unzip Vault binary
  ansible.builtin.unarchive:
    src: "/tmp/vault.zip"
    dest: "{{ vault_install_dir }}"
    remote_src: yes
    mode: 0755

- name: Create Vault group
  ansible.builtin.group:
    name: "{{ vault_group }}"
    state: present
    system: yes

- name: Create Vault user
  ansible.builtin.user:
    name: "{{ vault_user }}"
    group: "{{ vault_group }}"
    system: yes
    shell: /sbin/nologin
    create_home: no

- name: Create Vault directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: '0750'
  loop:
    - "{{ vault_config_dir }}"
    - "{{ vault_data_dir }}"
    - "{{ vault_config_ssl_dir }}"
