---
- name: Install Vault
  ansible.builtin.include_tasks:
    file: 'install.yml'
- name: Configure Vault
  ansible.builtin.include_tasks:
    file: 'configure.yml'
- name: Initialize Vault operator
  ansible.builtin.include_tasks:
    file: 'initialize_operator.yml'
  when: vault_auto_init_operator | default(false)
- name: Unseal Vault operator
  ansible.builtin.include_tasks:
    file: 'unseal.yml'
  when: vault_auto_init_operator | default(false)
