- name: Unseal Vault with unseal JSON file in Master node
  shell: |
    for key in $(jq -r '.unseal_keys_b64[]' "{{ vault_config_dir }}/unseal.json"); do
      vault operator unseal "$key" || true
    done
  environment:
    VAULT_ADDR: "{{ vault_api_addr }}"
  args:
    executable: /bin/bash
  register: unseal_master_result
  when:
    - is_vault_master_node

- name: Fetch unseal JSON file from Master node
  fetch:
    src: "{{ vault_config_dir }}/unseal.json"
    dest: /tmp/unseal.json
    flat: true
  when:
    - is_vault_master_node

- name: Copy unseal JSON file to Slave nodes
  copy:
    src: /tmp/unseal.json
    dest: "{{ vault_config_dir }}/unseal.json"
  when:
    - not is_vault_master_node

- name: Unseal Vault with unseal JSON file in Slave nodes
  shell: |
    for key in $(jq -r '.unseal_keys_b64[]' "{{ vault_config_dir }}/unseal.json"); do
      vault operator unseal "$key" || true
    done
  environment:
    VAULT_ADDR: "{{ vault_api_addr }}"
  args:
    executable: /bin/bash
  when:
    - not is_vault_master_node

- name: Remove unseal JSON file in Slave nodes
  ansible.builtin.file:
    path: "{{ vault_config_dir }}/unseal.json"
    state: absent
  when: not is_vault_master_node
