---
- name: Generate Teleport config
  ansible.builtin.template:
    src: teleport_config.yaml.j2
    dest: "{{ teleport_config_file }}"
    owner: "{{ teleport_user }}"
    group: "{{ teleport_group }}"
    mode: 0640

- name: Generate Teleport systemd service
  ansible.builtin.template:
    src: teleport.service.j2
    dest: /etc/systemd/system/teleport.service
    mode: 0644

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Ensure and start Teleport service
  ansible.builtin.systemd:
    name: teleport
    state: restarted
    enabled: yes
    daemon_reload: yes