---
- name: Install Elasticsearch
  ansible.builtin.include_tasks:
    file: 'install.yml'

- name: Configure Elasticsearch SSL
  ansible.builtin.include_tasks:
    file: 'ssl_configure.yml'

- name: Configure Elasticsearch
  ansible.builtin.include_tasks:
    file: 'configure.yml'

- name: Reset Elasticserch superuser password
  ansible.builtin.include_tasks:
    file: 'superuser_reset_password.yml'