---
- name: Copy Elasticsearch SSL certificate
  ansible.builtin.copy:
    src: "elasticsearch.crt"
    dest: "{{ elasticsearch_ssl_cert_file }}"
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    mode: 0640
  when: elasticsearch_ssl_enabled

- name: Copy Elasticsearch SSL key
  ansible.builtin.copy:
    src: "elasticsearch.key"
    dest: "{{ elasticsearch_ssl_key_file }}"
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    mode: 0600
  when: elasticsearch_ssl_enabled

- name: Copy Elasticsearch CA certificate
  ansible.builtin.copy:
    src: "elasticsearch-ca.crt"
    dest: "{{ elasticsearch_ssl_ca_file }}"
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    mode: 0644
  when: elasticsearch_ssl_enabled


- name: Copy Elasticsearch CA certificate to trusted CA (system-wide)
  ansible.builtin.copy:
    src: "elasticsearch-ca.crt"
    dest: "/usr/local/share/ca-certificates/elasticsearch-ca.crt"
    owner: root
    group: root
    mode: 0644
  when: elasticsearch_ssl_enabled

- name: Update Elasticearch trusted CA certificates
  ansible.builtin.command: update-ca-certificates
  register: update_ca_output
  changed_when: "'added new certificate' in update_ca_output.stdout"
  when: elasticsearch_ssl_enabled