---
- name: Wait for Elasticsearch to be ready by checking logs
  shell: |
    grep -q 'current.health="GREEN"' "/var/log/elasticsearch/{{ elasticsearch_cluster_name }}.log"
  register: es_log_check
  retries: 30
  delay: 5
  until: es_log_check.rc == 0
  when:
    - inventory_hostname == groups['elasticsearch'][0]

- name: Reset Elasticsearch elastic user password and save it
  shell: yes | "{{ elasticsearch_home_dir }}/bin/elasticsearch-reset-password" -u elastic
  register: reset_password_result

- name: Save Elasticsearch superuser password
  copy:
    content: "{{ reset_password_result.stdout }}"
    dest: "{{ elasticsearch_config_dir }}/elastic_password.txt"
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    mode: 0600
  when:
    - inventory_hostname == groups['elasticsearch'][0]