---
#- name: Run systemctl restart teleport
#  listen: 'systemctl restart teleport'
#  become: true
#  ansible.builtin.systemd_service:
#    name: 'teleport'
#    enabled: true
#    state: 'restarted'
#  notify: "systemctl restart teleport.service"
